# Generated by Django 3.0.4 on 2020-03-23 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projects',
            name='donated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='main_img_name',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='projects',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
