# Generated by Django 3.0.4 on 2020-03-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200318_0134'),
        ('users', '0002_auto_20200318_0125'),
        ('categories', '0002_auto_20200318_0134'),
        ('images', '0001_initial'),
        ('donations', '0002_auto_20200318_0134'),
        ('projects', '0002_auto_20200318_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='user_id',
            new_name='user',
        ),
    ]
