# Generated by Django 3.0.4 on 2020-03-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('projects', '0003_auto_20200318_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='projects',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tags.Tags'),
            preserve_default=False,
        ),
    ]
