# Generated by Django 3.0.4 on 2020-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200318_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total_donation',
            field=models.IntegerField(default=0),
        ),
    ]
