# Generated by Django 3.0.4 on 2020-03-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200318_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_Location',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
