# Generated by Django 3.0.4 on 2020-03-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200319_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='donate',
        ),
    ]
