# Generated by Django 3.0.4 on 2020-03-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='donated',
            field=models.IntegerField(default=0),
        ),
    ]
