# Generated by Django 3.0.4 on 2020-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200319_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='main_img_name',
            field=models.TextField(default=' '),
        ),
    ]
