# Generated by Django 3.0.4 on 2020-03-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200318_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_id',
            new_name='id',
        ),
    ]
