# Generated by Django 3.0.4 on 2020-03-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='project_id',
            new_name='project',
        ),
    ]
