# Generated by Django 3.0.4 on 2020-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Image_title',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='images',
            name='image_description',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
