# Generated by Django 3.0.4 on 2020-03-20 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default=' ', max_length=100)),
                ('user_img', models.ImageField(upload_to='user_images/')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.CharField(default='01', max_length=11, validators=[django.core.validators.RegexValidator(regex='^[+-]?[0-9]+$')])),
            ],
        ),
    ]
