# Generated by Django 3.0.4 on 2020-03-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=10)),
                ('user_lname', models.CharField(max_length=10)),
                ('user_picture', models.ImageField(upload_to='user_images/')),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
