# Generated by Django 3.0.4 on 2020-03-17 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_picture',
            new_name='user_img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_lname',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='01', max_length=11, validators=[django.core.validators.RegexValidator(regex='^[+-]?[0-9]+$')]),
        ),
    ]
