# Generated by Django 3.0.4 on 2020-03-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200318_0134'),
        ('projects', '0003_auto_20200318_0134'),
        ('donations', '0002_auto_20200318_0134'),
        ('users', '0002_auto_20200318_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
